sonar.verbose=true
sonar.organization=saidemy01
sonar.projectKey=saidemy01_irctc
sonar.projectName=irctc
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=cloning
sonar.java.binaries=cloning/target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.host.url=https://sonarcloud.io/
